### PR TITLE
optimizations: Fix GOA optimization messing with NWNX functionality

### LINKED ISSUE #801: NWNX_OPTIMIZATIONS_GAME_OBJECT_LOOKUP breaks NWNX_Util_GetLastCreatedObject() and NWNX_ON_DM_SPAWN_*
Both `GetLastCreatedObject()` and `NWNX_ON_DM_SPAWN_*` use `GetObjectArray()->m_nNextObjectArrayID[0]` to get the next ObjectID, since the `GameObjectLookup` optimization has its own implementation of `m_nNextObjectArrayID[]` these functions do not work if the optimization is enabled.

### PR DESCRIPTION
**Pull request by mtijanic**
Fixes #801  (well, I only tested the nwnx_utils part of it because that was possible from console, but should fix the other one)

### CODE REVIEW

File: Plugins/Optimizations/Optimizations/GameObjectLookup.cpp [hunk 1]
```diff
@@ -304,4 +311,15 @@ uint8_t GameObjectLookup::GetGameObject(void*, uint32_t id, CGameObject** ptr)
     return BadId;
 }
 
+void GameObjectLookup::SyncWithGameGOA()
+{
+    if (auto pGameObjectArray = Globals::AppManager()->m_pServerExoApp->GetObjectArray())
```
Comment (Daztek) [inline Plugins/Optimizations/Optimizations/GameObjectLookup.cpp]: Nitpick: missing the `*` :P

Comment (mtijanic) [reply Plugins/Optimizations/Optimizations/GameObjectLookup.cpp]: I copied it from your code. Fixed in both places :)
