### PR TITLE
ServerLogRedirector: fix timestamp trimming

### LINKED ISSUE #753: ServerLogRedirector discards chat [prefixes]
```
eval PrintString("[foo] aaa");
I [20:24:54] [NWNX_Core] Executing console command: 'eval' with args: PrintString("[foo] aaa");
I [20:24:54] [NWNX_ServerLogRedirector] (Server) aaa
```
https://github.com/nwnxee/unified/blob/master/Plugins/ServerLogRedirector/ServerLogRedirector.cpp#L52-L62

Code assumes people are using `WriteTimestampedLogEntry()` which adds a timestamp, but if you use PrintString and add a `[tag]` manually, it gets removed when printed to NWNX log.

### PR DESCRIPTION
**Pull request by Daztek**
Fixes #753

### CODE REVIEW

File: Plugins/ServerLogRedirector/ServerLogRedirector.cpp [hunk 1]
```diff
@@ -43,6 +43,9 @@ ServerLogRedirector::ServerLogRedirector(const Plugin::CreateParams& params)
 
     GetServices()->m_hooks->RequestSharedHook<Functions::_ZN17CExoDebugInternal16WriteToErrorFileERK10CExoString,
         void, CExoDebugInternal*, CExoString*>(&WriteToErrorFileHook);
+
+    GetServices()->m_hooks->RequestSharedHook<Functions::_ZN25CNWVirtualMachineCommands27ExecuteCommandPrintLogEntryEii,
+        int32_t>(&ExecuteCommandPrintLogEntry);
```
Comment (mtijanic) [inline Plugins/ServerLogRedirector/ServerLogRedirector.cpp]: Could just do a tiny inline lambda :)

File: Plugins/ServerLogRedirector/ServerLogRedirector.cpp [hunk 2]
```diff
@@ -34,6 +32,8 @@ using namespace NWNXLib;
 using namespace NWNXLib::API;
 using namespace NWNXLib::Services;
 
+static bool m_WriteTimestampedLogEntry;
```
Comment (mtijanic) [inline Plugins/ServerLogRedirector/ServerLogRedirector.cpp]: Nitiest of nits: `m_` is used for member fields. Statics sometimes use `s_`, or just no prefix at all.

File: Plugins/ServerLogRedirector/ServerLogRedirector.cpp (hunk 1 above)
Comment (Daztek) [reply Plugins/ServerLogRedirector/ServerLogRedirector.cpp]: Good idea :D
